import { NavLink, Link, useNavigate } from 'react-router-dom'
import { FiCompass, FiLogOut, FiMenu, FiX } from 'react-icons/fi'
import { useState } from 'react'
import { useAuth } from '../../context/AuthContext'

export default function DashboardLayout({ role, children }) {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const [open, setOpen] = useState(false)
  const links = role === 'customer' ? [['Overview', `/dashboard/customer`], ['Profile', `/dashboard/customer/profile`], ['Requests', `/dashboard/customer/requests`], ['Orders', `/dashboard/customer/orders`], ['Reviews', `/dashboard/customer/reviews`], ['Complaints', `/dashboard/customer/complaints`]] : role === 'entrepreneur' ? [['Overview', `/dashboard/entrepreneur`], ['Business profile', `/dashboard/entrepreneur/profile`], ['Services', `/dashboard/entrepreneur/services`], ['Products', `/dashboard/entrepreneur/products`], ['Requests', `/dashboard/entrepreneur/requests`], ['Orders', `/dashboard/entrepreneur/orders`], ['Reviews', `/dashboard/entrepreneur/reviews`]] : [['Overview', `/dashboard/admin`], ['Users', `/dashboard/admin/users`], ['Entrepreneurs', `/dashboard/admin/entrepreneurs`], ['Products', `/dashboard/admin/products`], ['Categories', `/dashboard/admin/categories`], ['Skills', `/dashboard/admin/skills`], ['Requests', `/dashboard/admin/requests`], ['Orders', `/dashboard/admin/orders`], ['Complaints', `/dashboard/admin/complaints`]]
  const signOut = async () => { await logout(); navigate('/') }
  return <div className="min-h-[calc(100vh-76px)] bg-[#fffaf3]"><button onClick={() => setOpen(!open)} aria-label="Toggle dashboard menu" className="fixed right-5 top-24 z-40 rounded-lg bg-stone-900 p-3 text-white md:hidden">{open ? <FiX /> : <FiMenu />}</button><aside className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 top-[76px] z-30 w-72 border-r border-orange-100 bg-white p-6 transition-transform md:translate-x-0`}><Link to="/" className="flex items-center gap-2 text-lg font-bold text-stone-900"><span className="grid h-8 w-8 place-items-center rounded-lg bg-orange-500 text-white"><FiCompass /></span>Hunar<span className="text-orange-500">Hub</span></Link><p className="mt-10 text-xs font-bold uppercase tracking-widest text-stone-400">{role} workspace</p><nav className="mt-4 grid gap-1">{links.map(([label, to]) => <NavLink onClick={() => setOpen(false)} end={to === `/dashboard/${role}`} key={to} to={to} className={({ isActive }) => `rounded-lg px-4 py-3 text-sm font-semibold ${isActive ? 'bg-orange-500 text-white' : 'text-stone-600 hover:bg-orange-50 hover:text-orange-600'}`}>{label}</NavLink>)}</nav><button onClick={signOut} className="mt-10 flex items-center gap-2 px-4 py-3 text-sm font-bold text-stone-500 hover:text-orange-600"><FiLogOut /> Log out</button></aside><main className="md:ml-72"><header className="flex items-center justify-between border-b border-orange-100 bg-white px-5 py-5 md:px-10"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-600">{role} dashboard</p><h1 className="display text-2xl font-bold text-stone-900">Good to see you, {user?.name?.split(' ')[0]}</h1></div><div className="grid h-10 w-10 place-items-center rounded-full bg-orange-100 font-bold text-orange-700">{user?.name?.charAt(0).toUpperCase()}</div></header><section className="mx-auto max-w-7xl px-5 py-8 md:px-10">{children}</section></main></div>
}