const express = require('express')
const { protect, authorize } = require('../middleware/authMiddleware')
const controller = require('../controllers/dashboardController')
const Service = require('../models/Service')
const Product = require('../models/Product')

const router = express.Router()
router.use(protect)
router.get('/customer', authorize('customer'), controller.customerDashboard)
router.get('/customer/resources', authorize('customer'), controller.customerResource)
router.post('/customer/services/:serviceId/requests', authorize('customer'), controller.createServiceRequest)
router.post('/customer/complaints', authorize('customer'), controller.createComplaint)
router.patch('/customer/requests/:id/status', authorize('customer'), controller.updateCustomerRequestStatus)
router.post('/customer/products/:productId/orders', authorize('customer'), controller.createOrder)
router.patch('/customer/orders/:id/status', authorize('customer'), controller.updateCustomerOrderStatus)
router.post('/customer/entrepreneurs/:entrepreneurId/reviews', authorize('customer'), controller.createReview)
router.get('/entrepreneur', authorize('entrepreneur'), controller.entrepreneurDashboard)
router.get('/entrepreneur/profile', authorize('entrepreneur'), controller.entrepreneurProfile)
router.put('/entrepreneur/profile', authorize('entrepreneur'), controller.updateEntrepreneurProfile)
router.get('/entrepreneur/services', authorize('entrepreneur'), controller.ownerResources(Service, 'entrepreneur'))
router.post('/entrepreneur/services', authorize('entrepreneur'), controller.createService)
router.put('/entrepreneur/services/:id', authorize('entrepreneur'), controller.updateService)
router.delete('/entrepreneur/services/:id', authorize('entrepreneur'), controller.deleteService)
router.get('/entrepreneur/products', authorize('entrepreneur'), controller.ownerResources(Product, 'entrepreneur', 'category'))
router.post('/entrepreneur/products', authorize('entrepreneur'), controller.createProduct)
router.put('/entrepreneur/products/:id', authorize('entrepreneur'), controller.updateProduct)
router.delete('/entrepreneur/products/:id', authorize('entrepreneur'), controller.deleteProduct)
router.get('/entrepreneur/resources', authorize('entrepreneur'), controller.entrepreneurResources)
router.patch('/entrepreneur/requests/:id/status', authorize('entrepreneur'), controller.updateRequestStatus)
router.patch('/entrepreneur/orders/:id/status', authorize('entrepreneur'), controller.updateOrderStatus)
router.get('/admin', authorize('admin'), controller.adminDashboard)
router.get('/admin/resources', authorize('admin'), controller.adminResources)
router.patch('/admin/complaints/:id/status', authorize('admin'), controller.updateComplaintStatus)
router.patch('/admin/entrepreneurs/:id/skills', authorize('admin'), controller.updateAdminEntrepreneurSkills)
router.patch('/admin/entrepreneurs/:id/verification', authorize('admin'), controller.updateEntrepreneurVerification)
router.delete('/admin/products/:id', authorize('admin'), controller.deleteAdminProduct)
router.post('/admin/categories', authorize('admin'), controller.categoryWrite)
router.put('/admin/categories/:id', authorize('admin'), controller.categoryWrite)
router.delete('/admin/categories/:id', authorize('admin'), controller.deleteCategory)

module.exports = router