import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { FiSearch, FiSliders } from 'react-icons/fi'
import { apiRequest } from '../../services/api'
import EntrepreneurCard from '../../components/marketplace/EntrepreneurCard'

export default function BrowseEntrepreneurs() {
  const [params] = useSearchParams(); const [people, setPeople] = useState([]); const [categories, setCategories] = useState([]); const [query, setQuery] = useState(params.get('search') || ''); const [category, setCategory] = useState(params.get('category') || ''); const [location, setLocation] = useState(params.get('location') || ''); const [max, setMax] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([apiRequest('/entrepreneurs'), apiRequest('/categories')]).then(([peopleResult, categoryResult]) => { setPeople(peopleResult.data); setCategories(categoryResult.data) }).catch(requestError => setError(requestError.message)).finally(() => setLoading(false)) }, [])
  const results = people.filter(person => `${person.businessName} ${person.description || ''} ${(person.skills || []).join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (!category || person.category?._id === category) && (!location || person.location?.toLowerCase().includes(location.toLowerCase())) && (!max || person.startingPrice <= Number(max)))
  return <div className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="max-w-2xl"><p className="font-bold uppercase tracking-widest text-orange-600">People behind the work</p><h1 className="display mt-2 text-4xl sm:text-5xl">Find your next favourite local expert.</h1><p className="mt-4 leading-7 text-stone-600">Browse trusted makers, fixers, and vendors ready to share their craft with you.</p></div><div className="mt-10 grid gap-3 rounded-2xl border border-orange-100 bg-white p-4 md:grid-cols-4"><label className="flex items-center gap-2 rounded-xl bg-stone-50 px-3"><FiSearch className="text-orange-500" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Name or skill" className="w-full bg-transparent py-3 text-sm outline-none" /></label><select value={category} onChange={event => setCategory(event.target.value)} className="rounded-xl bg-stone-50 px-3 py-3 text-sm outline-none"><option value="">All categories</option>{categories.map(item => <option key={item._id} value={item._id}>{item.name}</option>)}</select><input value={location} onChange={event => setLocation(event.target.value)} placeholder="Location" className="rounded-xl bg-stone-50 px-3 py-3 text-sm outline-none" /><select value={max} onChange={event => setMax(event.target.value)} className="rounded-xl bg-stone-50 px-3 py-3 text-sm outline-none"><option value="">Any starting price</option><option value="500">Under 500</option><option value="1000">Under 1,000</option><option value="1500">Under 1,500</option></select><button onClick={() => { setQuery(''); setCategory(''); setLocation(''); setMax('') }} className="flex items-center gap-2 text-sm font-bold text-orange-600 md:col-span-4"><FiSliders /> Clear filters</button></div>{loading ? <p className="py-16 text-center font-semibold text-orange-600">Loading entrepreneurs...</p> : error ? <p className="mt-10 rounded-xl bg-red-50 p-4 text-red-700">{error}</p> : <><h2 className="mt-12 text-xl font-bold">{results.length} entrepreneurs</h2>{results.length ? <div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{results.map(person => <EntrepreneurCard key={person._id} entrepreneur={{ id: person._id, name: person.user?.name || person.businessName, business: person.businessName, category: person.category?.name, location: person.location, rating: person.averageRating, price: person.startingPrice, verified: person.isVerified, image: person.profileImage || 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=80' }} />)}</div> : <p className="mt-6 text-stone-500">No entrepreneurs match these filters.</p>}</>}</div>
}