import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { FiArrowRight, FiCompass, FiHeart, FiShield, FiTag, FiUsers, FiStar } from 'react-icons/fi'
import { apiRequest } from '../../services/api'
import SearchBar from '../../components/common/SearchBar'

const fallbackImage = 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=80'
function State({ loading, error, empty }) { if (loading) return <p className="py-10 text-center font-semibold text-orange-600">Loading...</p>; if (error) return <p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>; if (empty) return <p className="py-10 text-center text-stone-500">No marketplace data yet.</p>; return null }

export default function Home() {
  const navigate = useNavigate(); const [query, setQuery] = useState(''); const [location, setLocation] = useState(''); const [data, setData] = useState({ entrepreneurs: [], products: [], categories: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([apiRequest('/entrepreneurs'), apiRequest('/products'), apiRequest('/categories')]).then(([entrepreneurResult, productResult, categoryResult]) => setData({ entrepreneurs: entrepreneurResult.data, products: productResult.data, categories: categoryResult.data })).catch(requestError => setError(requestError.message)).finally(() => setLoading(false)) }, [])
  const search = () => navigate(`/entrepreneurs?search=${encodeURIComponent(query)}&location=${encodeURIComponent(location)}`)
  return <><section className="pattern overflow-hidden px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="mb-5 text-sm font-bold uppercase tracking-[.18em] text-orange-600">Local hands, lasting impact</p><h1 className="display max-w-2xl text-5xl leading-[1.05] text-stone-900 sm:text-6xl">Discover Local Talent.<br /><span className="text-orange-500">Support Local Dreams.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-stone-600">Find skilled people in your neighbourhood, shop handmade, and help the small businesses that keep our communities full of character.</p><div className="mt-8 max-w-2xl"><SearchBar query={query} setQuery={setQuery} location={location} setLocation={setLocation} onSearch={search} /></div><Link to="/entrepreneurs" className="mt-6 inline-flex items-center gap-2 rounded-full bg-stone-900 px-6 py-3.5 font-bold text-white">Explore Local Talent <FiArrowRight /></Link></div><img src="https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=1000&q=85" alt="A craftsperson shaping a handmade object" className="h-[440px] w-full rounded-[2rem] object-cover shadow-2xl shadow-orange-200 lg:h-[520px]" /></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionTitle eyebrow="Find your kind of craft" title="Popular categories" /><State loading={loading} error={error} empty={!data.categories.length} />{!loading && !error && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{data.categories.slice(0, 5).map(category => <Link key={category._id} to={`/entrepreneurs?category=${category._id}`} className="rounded-2xl border border-orange-100 bg-white p-5 shadow-sm hover:border-orange-400"><FiTag className="text-2xl text-orange-500" /><h3 className="mt-4 font-bold">{category.name}</h3><p className="mt-2 text-sm text-stone-500">{category.description || 'Explore local makers and services.'}</p></Link>)}</div>}</section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionTitle eyebrow="People worth knowing" title="Featured entrepreneurs" /><State loading={loading} error={error} empty={!data.entrepreneurs.length} />{!loading && !error && <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{data.entrepreneurs.slice(0, 6).map(person => <Link key={person._id} to={`/entrepreneurs/${person._id}`} className="overflow-hidden rounded-2xl border border-orange-100 bg-white shadow-sm hover:-translate-y-1"><img src={person.profileImage || fallbackImage} alt={person.businessName} className="h-52 w-full object-cover" /><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-orange-600">{person.category?.name || 'Local expert'}</p><h3 className="mt-1 text-lg font-bold">{person.user?.name || person.businessName}</h3><p className="text-sm text-stone-500">{person.businessName}</p><span className="mt-4 flex items-center gap-1 text-sm font-semibold text-amber-600"><FiStar fill="currentColor" /> {person.averageRating || 0}</span></div></Link>)}</div>}</section>
  <section className="bg-stone-100 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Made nearby" title="Handmade products" /><State loading={loading} error={error} empty={!data.products.length} />{!loading && !error && <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{data.products.slice(0, 4).map(product => <Link key={product._id} to={`/entrepreneurs/${product.entrepreneur?._id}`} className="overflow-hidden rounded-2xl border border-orange-100 bg-white shadow-sm hover:-translate-y-1"><img src={product.images?.[0] || fallbackImage} alt={product.name} className="h-56 w-full object-cover" /><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-orange-600">{product.category?.name}</p><h3 className="mt-1 font-bold">{product.name}</h3><p className="mt-4 font-bold">{product.price}</p></div></Link>)}</div>}</div></section>
  <section className="bg-orange-50 px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3">{[[FiCompass, 'Discover', 'Find skilled local entrepreneurs near you.'], [FiUsers, 'Connect', 'Explore profiles, services, and handmade products.'], [FiHeart, 'Support', 'Request services and support local businesses.']].map(([Icon, title, text]) => <div key={title} className="text-center"><Icon className="mx-auto text-3xl text-orange-500" /><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-2 text-stone-600">{text}</p></div>)}</div></section><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-8 md:grid-cols-4">{[[FiCompass, 'Discover Local Skills'], [FiHeart, 'Support Small Businesses'], [FiTag, 'Transparent Pricing'], [FiShield, 'Trusted Community']].map(([Icon, title]) => <div key={title}><Icon className="text-2xl text-orange-500" /><h3 className="mt-4 font-bold">{title}</h3></div>)}</div></section></>
}
function SectionTitle({ eyebrow, title }) { return <div className="mb-8"><p className="font-bold uppercase tracking-widest text-orange-600">{eyebrow}</p><h2 className="display mt-2 text-3xl sm:text-4xl">{title}</h2></div> }